# Sourced by [hook] on-activate. Must be idempotent and silent on the happy path.

export OLLAMA_CONTEXT_LENGTH="${OLLAMA_CONTEXT_LENGTH:-32768}"
export OLLAMA_HOST="127.0.0.1"
export OLLAMA_PORT="${OLLAMA_PORT:-11434}"
export OPENAI_API_BASE="${OPENAI_API_BASE:-http://127.0.0.1:11434/v1}"
export OPENAI_API_KEY="${OPENAI_API_KEY:-ollama}"
export OMLX_HOST="${OMLX_HOST:-127.0.0.1}"
export OMLX_PORT="${OMLX_PORT:-8000}"
export LLAMACPP_PROXY_OLLAMA_LISTEN="${LLAMACPP_PROXY_OLLAMA_LISTEN:-127.0.0.1:8081}"
export LLAMACPP_PROXY_GEMINI_OLLAMA_LISTEN="${LLAMACPP_PROXY_GEMINI_OLLAMA_LISTEN:-127.0.0.1:8082}"
export LLAMACPP_PROXY_OMLX_LISTEN="${LLAMACPP_PROXY_OMLX_LISTEN:-127.0.0.1:8083}"
export LLAMACPP_PROXY_GEMINI_OMLX_LISTEN="${LLAMACPP_PROXY_GEMINI_OMLX_LISTEN:-127.0.0.1:8084}"
